"""empty message

Revision ID: 13e8c91d98a0
Revises: fbbff5e9fd39
Create Date: 2024-10-27 22:12:35.697371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e8c91d98a0'
down_revision = 'fbbff5e9fd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_dates', schema=None) as batch_op:
        batch_op.drop_index('race_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_dates', schema=None) as batch_op:
        batch_op.create_index('race_date', ['race_date'], unique=True)

    # ### end Alembic commands ###
