"""empty message

Revision ID: 3a30fec9193f
Revises: 41aae79b7ac9
Create Date: 2024-10-23 16:58:34.536131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a30fec9193f'
down_revision = '41aae79b7ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_ave_info', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint(None, ['horse_id'])
        batch_op.drop_column('order_ave')

    with op.batch_alter_table('jockey', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['jockey_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jockey', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('horse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_ave', mysql.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('order_ave_info')

    # ### end Alembic commands ###
