"""empty message

Revision ID: 41aae79b7ac9
Revises: 
Create Date: 2024-07-25 14:46:11.153186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aae79b7ac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.String(length=255), nullable=True),
    sa.Column('order_ave', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jockey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jockey_id', sa.String(length=255), nullable=True),
    sa.Column('old', sa.Integer(), nullable=True),
    sa.Column('top_ratio', sa.Float(), nullable=True),
    sa.Column('victory_ratio', sa.Float(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=255), nullable=True),
    sa.Column('order', sa.String(length=255), nullable=True),
    sa.Column('horse_name', sa.String(length=255), nullable=True),
    sa.Column('horse_id', sa.String(length=255), nullable=True),
    sa.Column('jockey_name', sa.String(length=255), nullable=True),
    sa.Column('jockey_id', sa.String(length=255), nullable=True),
    sa.Column('odds', sa.String(length=255), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('predict_frag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_result')
    op.drop_table('jockey')
    op.drop_table('horse')
    # ### end Alembic commands ###
