"""empty message

Revision ID: 5359906d8dd5
Revises: cbe5f1b82725
Create Date: 2024-11-29 14:03:50.924603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5359906d8dd5'
down_revision = 'cbe5f1b82725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_race_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=255), nullable=False),
    sa.Column('race_date', sa.String(length=255), nullable=False),
    sa.Column('start_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race_dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_at', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_dates', schema=None) as batch_op:
        batch_op.drop_column('start_at')

    op.drop_table('temporary_race_data')
    # ### end Alembic commands ###
