"""empty message

Revision ID: 7065748dac5f
Revises: 9d78add4a79d
Create Date: 2024-10-27 15:31:12.209218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7065748dac5f'
down_revision = '9d78add4a79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_title', sa.String(length=255), nullable=False),
    sa.Column('race_date', sa.String(length=255), nullable=False),
    sa.Column('race_id', sa.String(length=255), nullable=False),
    sa.Column('top_ratio', sa.Float(), nullable=True),
    sa.Column('victory_ratio', sa.Float(), nullable=True),
    sa.Column('box_ratio', sa.Float(), nullable=True),
    sa.Column('recovery_rate', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predict_result')
    # ### end Alembic commands ###
