"""empty message

Revision ID: 73a2aab6796f
Revises: ccd77ee59448
Create Date: 2024-10-25 05:33:57.670414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a2aab6796f'
down_revision = 'ccd77ee59448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_dates', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
