"""empty message

Revision ID: 9d872a2dd37f
Revises: 5359906d8dd5
Create Date: 2024-12-11 14:44:53.420439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d872a2dd37f'
down_revision = '5359906d8dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_race_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_info', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_race_data', schema=None) as batch_op:
        batch_op.drop_column('race_info')

    # ### end Alembic commands ###
