"""empty message

Revision ID: ccd77ee59448
Revises: 3a30fec9193f
Create Date: 2024-10-24 21:19:51.562542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd77ee59448'
down_revision = '3a30fec9193f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_date', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_dates')
    # ### end Alembic commands ###
