"""empty message

Revision ID: fbbff5e9fd39
Revises: 7065748dac5f
Create Date: 2024-10-27 16:59:18.814450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbff5e9fd39'
down_revision = '7065748dac5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('race_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_dates', schema=None) as batch_op:
        batch_op.drop_column('race_id')
        batch_op.drop_column('race_title')

    # ### end Alembic commands ###
