"""empty message

Revision ID: 8d2e660e2f4e
Revises: 
Create Date: 2024-07-21 17:11:15.268094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d2e660e2f4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('race_id',
               existing_type=mysql.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('order',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('horse_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('jockey_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('odds',
               existing_type=mysql.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('race_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_result', schema=None) as batch_op:
        batch_op.alter_column('race_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('odds',
               existing_type=sa.Float(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('jockey_name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('horse_name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('order',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('race_id',
               existing_type=sa.Integer(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('expires_at')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
