"""empty message

Revision ID: 9e5599a2f60f
Revises: 8d2e660e2f4e
Create Date: 2024-07-22 12:41:12.247677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e5599a2f60f'
down_revision = '8d2e660e2f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_result',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('race_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('order', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('horse_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('jockey_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('odds', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('race_date', mysql.DATETIME(), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
